### ISSUE TITLE
NPE on MjpegViewDefault

### ISSUE THREAD

**Issue by dmolinaa** [niqdev/ipcam-view#12]
Hi! When you go to background and then back to foreground there a NPE. This is because when you call _surfaceDestroyed, the thread is set to null then when you back to foreground you call thread.star() and thread is null.

The logs:
 `07-03 02:30:47.794 15369-15369/com.github.niqdev.ipcam E/IpCamDefaultActivity: mjpeg error
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method '07-03 02:30:47.794 15369-15369/com.github.niqdev.ipcam E/IpCamDefaultActivity: mjpeg error
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.niqdev.mjpeg.MjpegViewDefault$MjpegViewThread.start()' on a null object reference
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._startPlayback(MjpegViewDefault.java:186)
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._setSource(MjpegViewDefault.java:238)
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault.setSource(MjpegViewDefault.java:283)
                                                                                   at com.github.niqdev.mjpeg.MjpegSurfaceView.setSource(MjpegSurfaceView.java:67)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity.lambda$loadIpCam$0(IpCamDefaultActivity.java:48)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity.access$lambda$0(IpCamDefaultActivity.java:0)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity$$Lambda$1.call(Unknown Source)
                                                                                   at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                                                                                   at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-03 02:30:47.871 15369-15369/com.github.niqdev.ipcam E/IpCamDefaultActivity: mjpeg error
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.niqdev.mjpeg.MjpegViewDefault$MjpegViewThread.start()' on a null object reference
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._startPlayback(MjpegViewDefault.java:186)
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._setSource(MjpegViewDefault.java:238)
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault.setSource(MjpegViewDefault.java:283)
                                                                                   at com.github.niqdev.mjpeg.MjpegSurfaceView.setSource(MjpegSurfaceView.java:67)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity.lambda$loadIpCam$0(IpCamDefaultActivity.java:48)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity.access$lambda$0(IpCamDefaultActivity.java:0)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity$$Lambda$1.call(Unknown Source)
                                                                                   at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                                                                                   at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-03 02:30:48.168 15369-15369/com.github.niqdev.ipcam E/IpCamDefaultActivity: mjpeg error
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.niqdev.mjpeg.MjpegViewDefault$MjpegViewThread.start()' on a null object reference
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._startPlayback(MjpegViewDefault.java:186)
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault._setSource(MjpegViewDefault.java:238)
                                                                                   at com.github.niqdev.mjpeg.MjpegViewDefault.setSource(MjpegViewDefault.java:283)
                                                                                   at com.github.niqdev.mjpeg.MjpegSurfaceView.setSource(MjpegSurfaceView.java:67)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity.lambda$loadIpCam$0(IpCamDefaultActivity.java:48)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity.access$lambda$0(IpCamDefaultActivity.java:0)
                                                                                   at com.github.niqdev.ipcam.IpCamDefaultActivity$$Lambda$1.call(Unknown Source)
                                                                                   at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                                   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                                                                                   at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-03 02:30:54.360 15369-15369/com.github.niqdev.ipcam D/AndroidRuntime: Shutting down VM
07-03 02:30:54.368 15369-15369/com.github.niqdev.ipcam E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.github.niqdev.ipcam, PID: 15369
                                                                         java.lang.RuntimeException: Unable to pause activity {com.github.niqdev.ipcam/com.github.niqdev.ipcam.IpCamDefaultActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.niqdev.mjpeg.MjpegViewDefault$MjpegViewThread.join()' on a null object reference
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
                                                                             at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
                                                                             at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.niqdev.mjpeg.MjpegViewDefault$MjpegViewThread.join()' on a null object reference
                                                                             at com.github.niqdev.mjpeg.MjpegViewDefault._stopPlayback(MjpegViewDefault.java:201)
                                                                             at com.github.niqdev.mjpeg.MjpegViewDefault.stopPlayback(MjpegViewDefault.java:298)
                                                                             at com.github.niqdev.mjpeg.MjpegSurfaceView.stopPlayback(MjpegSurfaceView.java:82)
                                                                             at com.github.niqdev.ipcam.IpCamDefaultActivity.onPause(IpCamDefaultActivity.java:69)
                                                                             at android.app.Activity.performPause(Activity.java:6363)
                                                                             at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
                                                                             at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340) 
                                                                             at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315) 
                                                                             at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by niqdev** [comment]
Hi,
I think the error is the same as this [issue](https://github.com/niqdev/ipcam-view/pull/8).
From your stacktrace, the NPE seems to happen not on `_surfaceDestroyed` but on `_startPlayback` at [line 186](https://github.com/niqdev/ipcam-view/blob/master/mjpeg-view/src/main/java/com/github/niqdev/mjpeg/MjpegViewDefault.java). I will fix the error and update the library soon.
Thanks

**Comment by niqdev** [comment]
Library version v0.3.3 should fix the problem and app version 1.2.2 is available for beta testing
