### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by vipamine33** [niqdev/ipcam-view#50]
I followed the instructions but the app crashes
the OnCreate() is called and the crash happens after that

here is the problem

E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
                  Process: app.example.com.rccontrol, PID: 10003
                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:776)
                   Caused by: java.lang.NoSuchMethodError: No static method com_github_niqdev_mjpeg_Mjpeg$$Lambda$1_lambda$connect$0(Lcom/github/niqdev/mjpeg/Mjpeg;Ljava/lang/String;)Lrx/Observable; in class Lcom/github/niqdev/mjpeg/Mjpeg; or its super classes (declaration of 'com.github.niqdev.mjpeg.Mjpeg' appears in /data/app/app.example.com.rccontrol-1/base.apk)
                      at com.github.niqdev.mjpeg.Mjpeg$$Lambda$1.call(Unknown Source)
                      at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
                      at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                      at rx.Observable.unsafeSubscribe(Observable.java:10256)
                      at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
                      at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:776)

**Comment by niqdev** [comment]
Hi, did you try the sample app in the project?
Here is an [example](https://github.com/niqdev/ipcam-view/blob/master/app/src/main/java/com/github/niqdev/ipcam/IpCamDefaultActivity.java)

If is not working I need the snippet of the code that cause the error and an explanation to regenerate it.
Thanks

**Comment by vipamine33** [comment]
i even imported that class into my app but same problem ( i tried it with and without ButterKnife)
[Here is the code ](https://github.com/vipamine33/IP-Cam-Viewer)

also i tried to download you app and modify on it but i cant get it to work on android studio :/

**Comment by niqdev** [comment]
Just to be sure, have you downloaded also the sample app from the play store and tested with your ip address?
Try also to remove
```
jackOptions {
  enabled true
}
```

**Comment by vipamine33** [comment]
Yea i tested the app and it works , i gave up and downloaded your app and used the default class there 
ill post if i find the solution 
Thank alot for the help tho ^^

**Comment by niqdev** [comment]
ok, feel free to re-open the issue if you find the problem, thanks
