### ISSUE TITLE
Failing after back button pressed

### ISSUE THREAD

**Issue by casic** [niqdev/ipcam-view#64]
When i test  and press back to go previous activity . onPause() method  

void onPause() {
        super.onPause();
        mjpegView.stopPlayback();
    }

and . CRASH

**Comment by casic71** [comment]
Hi,   this is in test and in my app. 
But i added  

StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
StrictMode.setThreadPolicy(policy);

in calling activity  and now i can back to  first activity .

**Comment by casic71** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.github.niqdev.ipcam, PID: 12069
                  android.os.NetworkOnMainThreadException
                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
                      at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:249)
                      at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
                      at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
                      at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                      at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                      at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
                      at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                      at com.android.okhttp.okio.RealBufferedSource.request(RealBufferedSource.java:71)
                      at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
                      at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
                      at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
                      at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
                      at com.android.okhttp.internal.Util.skipAll(Util.java:176)
                      at com.android.okhttp.internal.Util.discard(Util.java:158)
                      at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:499)
                      at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:374)
                      at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:362)
                      at java.io.BufferedInputStream.close(BufferedInputStream.java:141)
                      at java.io.FilterInputStream.close(FilterInputStream.java:64)
                      at com.github.niqdev.mjpeg.MjpegViewDefault._stopPlayback(MjpegViewDefault.java:264)
                      at com.github.niqdev.mjpeg.MjpegViewDefault._surfaceDestroyed(MjpegViewDefault.java:280)
                      at com.github.niqdev.mjpeg.MjpegViewDefault.onSurfaceDestroyed(MjpegViewDefault.java:358)
                      at com.github.niqdev.mjpeg.MjpegSurfaceView.surfaceDestroyed(MjpegSurfaceView.java:94)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:566)
                      at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:239)
                      at android.view.View.dispatchWindowVisibilityChanged(View.java:9641)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1309)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1383)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by casic71** [comment]
Also  when there is an errors in stream , no handle event . Just white screen . No way to stop or show  message  ???

**Comment by niqdev** [comment]
Please, look at the sample app, there is an [example](https://github.com/niqdev/ipcam-view/blob/master/app/src/main/java/com/github/niqdev/ipcam/IpCamDefaultActivity.java#L57) of how to handle errors

**Comment by niqdev** [comment]
Feel free to re-open the issue and provide more information of your problem
