### ISSUE TITLE
Issue When I request to access IP again

### ISSUE THREAD

**Issue by KeplerCollections** [niqdev/ipcam-view#88]
2019-12-26 16:07:59.016 27211-27474/com.simonixlabs.smarthome E/Mjpeg: error during connection
    java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
        at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:336)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:885)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:498)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:434)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
        at com.github.niqdev.mjpeg.Mjpeg.lambda$connect$0$Mjpeg(Mjpeg.java:118)
        at com.github.niqdev.mjpeg.-$$Lambda$Mjpeg$ciIfwbSmSGAtW1PTgDP7ccdMqCs.call(Unknown Source:4)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback.call(OnSubscribeTimeoutTimedWithFallback.java:64)
        at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback.call(OnSubscribeTimeoutTimedWithFallback.java:36)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-12-26 16:08:00.612 27211-27211/com.simonixlabs.smarthome W/System.err: java.util.concurrent.TimeoutException
2019-12-26 16:08:00.614 27211-27211/com.simonixlabs.smarthome W/System.err:     at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback$TimeoutMainSubscriber.onTimeout(OnSubscribeTimeoutTimedWithFallback.java:166)
2019-12-26 16:08:00.615 27211-27211/com.simonixlabs.smarthome W/System.err:     at rx.internal.operators.OnSubscribeTimeoutTimedWithFallback$TimeoutMainSubscriber$TimeoutTask.call(OnSubscribeTimeoutTimedWithFallback.java:191)
2019-12-26 16:08:00.616 27211-27211/com.simonixlabs.smarthome W/System.err:     at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
2019-12-26 16:08:00.617 27211-27211/com.simonixlabs.smarthome W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
2019-12-26 16:08:00.618 27211-27211/com.simonixlabs.smarthome W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
2019-12-26 16:08:00.619 27211-27211/com.simonixlabs.smarthome W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-26 16:08:00.620 27211-27211/com.simonixlabs.smarthome W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-12-26 16:08:00.620 27211-27211/com.simonixlabs.smarthome W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-12-26 16:08:00.621 27211-27211/com.simonixlabs.smarthome W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-26 16:08:00.622 27211-27211/com.simonixlabs.smarthome W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by jayesh83** [comment]
Yes facing the same issue

**Comment by jayesh83** [comment]
Whenever the address is not reachable it crashes the app
